### ISSUE TITLE
why was the mitm mode removed

### ISSUE THREAD

**Issue by un-simp** [WorldObservationLog/AppleMusicDecrypt#11]
Hi, Just wondering why the mitm mode has been removed as it was a feature i was planning to use and noticed was removed in recent commits

**Comment by WorldObservationLog** [comment]
Cause now the script can get the best m3u8 from device. No need to use mitm mode to get the m3u8

**Comment by un-simp** [comment]
Ah. i thought it was using it for fairplay decryption. nevermind
