### ISSUE TITLE
wrong handler name

### ISSUE THREAD

**Issue by loooop11** [WorldObservationLog/AppleMusicDecrypt#14]
handler name does not show Core Media Audio. Instead, it just shows the song title. Please fix this issue.

Audio
ID                        : 2
Format                    : AAC LC
Format/Info               : Advanced Audio Codec
Codec ID                  : mp4a-40-2
Duration                  : 3 min 5 s
Duration_LastFrame        : -17 ms
Bit rate mode             : Variable
Bit rate                  : 252 kb/s
Maximum bit rate          : 306 kb/s
Channel(s)                : 2 channels
Channel layout            : L R
Sampling rate             : 44.1 kHz
Frame rate                : 43.066 FPS (1024 SPF)
Compression mode          : Lossy
Stream size               : 5.58 MiB (83%)
**Title                     : Cooped Up (feat. Roddy Ricch)**
Default                   : Yes
Alternate group           : 1
Encoded date              : 2024-04-19 04:05:18 UTC
Tagged date               : 2024-04-19 04:05:18 UTC

**Comment by loooop11** [comment]
Also, I see some ripped AAC songs have a 48kHz sampling rate. Why? Is the source file stored on their server has same sampling rate as the one being downloaded?

Audio
ID                        : 2
Format                    : AAC LC
Format/Info               : Advanced Audio Codec
Codec ID                  : mp4a-40-2
Duration                  : 2 min 19 s
Duration_LastFrame        : -9 ms
Bit rate mode             : Variable
Bit rate                  : 252 kb/s
Maximum bit rate          : 279 kb/s
Channel(s)                : 2 channels
Channel layout            : L R
**_Sampling rate             : 48.0 kHz_**
Frame rate                : 46.875 FPS (1024 SPF)
Compression mode          : Lossy
Stream size               : 4.19 MiB (74%)
Title                     : Let's Go (Remix)
Default                   : Yes
Alternate group           : 1
Encoded date              : 2024-04-11 12:45:14 UTC
Tagged date               : 2024-04-11 12:45:14 UTC

**Comment by WorldObservationLog** [comment]
> Also, I see some ripped AAC songs have a 48kHz sampling rate. Why? Is the source file stored on their server has same sampling rate as the one being downloaded?
> 
> Audio ID : 2 Format : AAC LC Format/Info : Advanced Audio Codec Codec ID : mp4a-40-2 Duration : 2 min 19 s Duration_LastFrame : -9 ms Bit rate mode : Variable Bit rate : 252 kb/s Maximum bit rate : 279 kb/s Channel(s) : 2 channels Channel layout : L R **_Sampling rate : 48.0 kHz_** Frame rate : 46.875 FPS (1024 SPF) Compression mode : Lossy Stream size : 4.19 MiB (74%) Title : Let's Go (Remix) Default : Yes Alternate group : 1 Encoded date : 2024-04-11 12:45:14 UTC Tagged date : 2024-04-11 12:45:14 UTC

Yes. In the original, encrypted audio, the sample rate is 48khz.
![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/115352805/0c041468-76f5-4003-b305-6727a03c84f1)

**Comment by WorldObservationLog** [comment]
> handler name does not show Core Media Audio. Instead, it just shows the song title. Please fix this issue.
> 
> Audio ID : 2 Format : AAC LC Format/Info : Advanced Audio Codec Codec ID : mp4a-40-2 Duration : 3 min 5 s Duration_LastFrame : -17 ms Bit rate mode : Variable Bit rate : 252 kb/s Maximum bit rate : 306 kb/s Channel(s) : 2 channels Channel layout : L R Sampling rate : 44.1 kHz Frame rate : 43.066 FPS (1024 SPF) Compression mode : Lossy Stream size : 5.58 MiB (83%) **Title : Cooped Up (feat. Roddy Ricch)** Default : Yes Alternate group : 1 Encoded date : 2024-04-19 04:05:18 UTC Tagged date : 2024-04-19 04:05:18 UTC

I don't think it's a bug. But anyway I will add a config item to change the behavior of script soon.
