### ISSUE TITLE
Date Format and Disc folders

### ISSUE THREAD

**Issue by zhordon** [WorldObservationLog/AppleMusicDecrypt#15]
Adjust settings in the config.toml file, I may have discovered a bug but also don't know if it's by design. As i know this is a WIP development I thought I'd seek some clarity

I'm trying to recreate my folder structure as close to what I have used in Orpheus which is the following: 

{artist} - {name}{explicit} ({release_year}) - {quality} = Artists - Track Title (Explicit) (2024) - ALAC

So to replicate that I used the following: 

dirPathFormat = "downloads/{album_artist} - {album} {created} - {codec}" = Artist - Album Title (2024-02-21) - ALAC

Q1. Is there a way to get {created} to display the YEAR only?

This is where the bug issue may come into play. When you use both the {created} and {disc} tags you get a weird output. The example code for this is: dirPathFormat = "downloads/{album_artist} - {album} {created} - {codec}/{disc}"

You get something to this effect with the same album:

Album Artist - Album Title (2024-02-21) - ALAC > 1 > 3 tracks
Album Artist - Album Title (2024-03-28) - ALAC > 1> 1 track
Album Artist - Album Title (2024-05-31) - ALAC > 1 > 12 tracks

![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/171749704/7c0e50de-6a0a-44fb-abcb-57ed3fa031d8)
![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/171749704/5dc3137a-6348-49c5-a6aa-c4f98fd58f22)
![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/171749704/57feffa8-ec4c-4f59-9f5a-a6a4f0ee70e8)
![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/171749704/c8c39e58-3a0f-4b66-b738-a6e5e5232c8f)
![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/171749704/b82f8eaf-d6ad-4138-825f-198e10e61d27)

As you can see with the images provided you end up with multiple folders and in each of the folders has a folder "1" and the tracks are scattered across different folder dates.

Q2a. Is that by design or is this a bug?

Q2b. Would this be resolved if only using the YEAR tag was available?

Q3c. Does AMD automatically make disc folders if an album has 2 or more discs? I download an album that had 2 discs but without disc tag It created 2 Album folders but with different created dates. 

![image](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/171749704/5941017d-4259-4976-abea-d2330e3e6d58)

What would be the appropriate method to create the following folder structure?: 

First Layer - Album Artist - Album Title - Year - ALAC
Second Layer - Album Artist - Album Title - Year - ALAC / Disc 1 / D1 Tracks
Second Layer - Album Artist - Album Title - Year - ALAC / Disc 2 / D2 tracks

Thanks for your time and efforts!

**Comment by WorldObservationLog** [comment]
As a temporary solution, you can now use `album_created` which does not change between songs within the same album.
