### ISSUE TITLE
File download or dlf doesn't work

### ISSUE THREAD

**Issue by Gamer4Life2020** [WorldObservationLog/AppleMusicDecrypt#16]
![dlf](https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/36717721/49b61903-5784-429c-a680-64ddc3066a2e)

Also, no big deal but is there a way to add the rating metadata like itunes advisory 0/1 or exp/non-exp, if not the data maybe the folder?
I don't need the folder though would be nice, but I use Picard and can pull from the metadata.

**Comment by zhordon** [comment]
dlf command doesn't seem to work, but download-from-file urls.txt seems to work.

**Comment by Gamer4Life2020** [comment]
> dlf command doesn't seem to work, but download-from-file urls.txt seems to work.

Well I guess I'm not typing something right as dl urls.txt or dl full path\urls.txt all fail.
No big deal but would be convenient for bulk artist/albums.

**Comment by zhordon** [comment]
> > dlf command doesn't seem to work, but download-from-file urls.txt seems to work.
> 
> Well I guess I'm not typing something right as dl urls.txt or dl full path\urls.txt all fail. No big deal but would be convenient for bulk artist/albums.

Bulk downloading works just fine. I actually did it last night. Here is the example that worked:

"download-from-file C:\Users\Name\MusicDL\AMD\downloads\urls.txt"

Replace the C:\ with your own file.

"dlf urls.txt" doesn't work for me.

If you do --help you will see download options available.

**Comment by Gamer4Life2020** [comment]
Strange, still doesn't work. I'll see if there is a newer release and try again.
<img width="662" alt="Capture" src="https://github.com/WorldObservationLog/AppleMusicDecrypt/assets/36717721/0180c85d-9372-4609-8a40-625730bbed43">

**Comment by zhordon** [comment]
Use the latest pre-compiled version from Actions.On Jun 11, 2024, at 5:52 PM, Gamer4Life2020 ***@***.***> wrote:﻿
Strange, still doesn't work. I'll see if there is a newer release and try again.
Capture.PNG (view on web)

**Comment by Gamer4Life2020** [comment]
Nice that works now. Thanks.
