### ISSUE TITLE
Anyway to use quality to check and get both versions if ALAC and Atmos

### ISSUE THREAD

**Issue by Gamer4Life2020** [WorldObservationLog/AppleMusicDecrypt#17]
Would there be a way in the future it not to hard to implement, maybe with the quality setting to be able to get both versions of an album like ALAC/EC3/AC3 like this album is both depending on how you download it.

https://music.apple.com/us/album/weezer/1440878798

**Comment by WorldObservationLog** [comment]
Just edit the configuration to ensure that files with different encodings are not saved with the same file name in the same path. Then use the -c parameter to specify the codec to download audio with different codecs at the same time.
