### ISSUE TITLE
[feature request] look into supporting workflow with Waydroid on Linux

### ISSUE THREAD

**Issue by kode54** [WorldObservationLog/AppleMusicDecrypt#21]
I’m not sure if Magisk will be needed for Waydroid use. Basically you only need to hide the appearance of a rooted device from Apple Music, even though technically Waydroid isn’t really rooted. It needs the waydroid base props listed in a “unroot” issue on their tracker. It also sets up network based adb to the lxc hosting the “device” and connects to it on session start, so there is no need to connect to it manually.

**Comment by WorldObservationLog** [comment]
I know very little about Waydriod. But it should be possible to install it in the same way as on the Google Android Emulator

**Comment by kode54** [comment]
I will attempt to use it with that. All it needs is to set up the system/vendor images (automatic), configure the un-rooting properties (search their issue tracker for un-root, the container isn’t really rooted per se, but doesn’t really impose the restrictions of a normal Android device, either. It just needs some properties overrides to hide from Apple Music’s root check) and enabling “usb” debugging for the host machine. (Waydroid script connects adb to it on startup, you just need to authorize it in the container like and generic Android device.)

if this script can work with Waydroid like it works with the Android Studio emulator, great. I’ll see what I can do and report back.
