### ISSUE TITLE
dependence adb was not installed

### ISSUE THREAD

**Issue by gowthamgulshan** [WorldObservationLog/AppleMusicDecrypt#24]
Hi there, I installed all the required WSA and modules but when i run main.exe following error shows "dependence adb was not installed"

**Comment by WorldObservationLog** [comment]
As prompted, please install the dependencies

**Comment by gowthamgulshan** [comment]
I'm sorry I didn't understand the adb dependencies I did everything can u
tell me what's the adb dependencies
