### ISSUE TITLE
Failing to decrypt

### ISSUE THREAD

**Issue by ngagne** [WorldObservationLog/AppleMusicDecrypt#7]
Hi, I've followed the guide a few times and verified all of the programs are running as expected. I installed the Apple Music beta, logged into my paid account, set audio quality to lossless, played a track, etc. Everything seems to be working when I start the script, but it fails on the decryption part. What can I do to debug decryption failure?

**Comment by ngagne** [comment]
yes, seems to fail when decrypting the sample

**Comment by WorldObservationLog** [comment]
It's a common problem. Try to restart the script and download it

**Comment by ngagne** [comment]
Thanks for your response. Here is the error I'm seeing:
```
2024-05-15 18:18:56.588 | ERROR    | asyncio.events:_run:84 - An error has been caught in function '_run', process 'MainProcess' (33952), thread 'MainThread' (8562801344):

FileNotFoundError: [Errno 2] No such file or directory: 'gpac -i /var/folders/0n/f8g9pd6959z1mv5mm4t9rpwm0000gn/T/tmpf6w8b1_5/4e6a4cd026634be29438813fc13e972b.mp4 nhmlw:pckp=true -o /var/folders/0n/f8g9pd6959z1mv5mm4t9rpwm0000gn/T/tmpf6w8b1_5/4e6a4cd026634be29438813fc13e972b.nhml'
```

**Comment by ngagne** [comment]
I've tried this on Windows x64 and MacOS arm64, but I'm continuing to face the same error above.

**Comment by WorldObservationLog** [comment]
Please check the following precautions:
- [ ]  Android Emulator for x86_64 architecture, without Google API
- [ ]  Apple Music Android 3.6.0-beta x86_64
- [ ]  Already login your Apple Music account and has a vaild subscription
- [ ]  Can play music normally in Apple Music in the simulator

**Comment by WorldObservationLog** [comment]
closed due to no progress
