### ISSUE TITLE
'-c aac' would output broken mp4a

### ISSUE THREAD

**Issue by TypesTse** [WorldObservationLog/AppleMusicDecrypt#9]
eg: https://music.apple.com/us/album/bad-romance/1476727669?i=1476727670

There would be no issue for the ALAC output, only the AAC would be broken. Tested based on the latest master version.

**Comment by WorldObservationLog** [comment]
Play normally on PotPlayer. Which player do you use?

**Comment by WorldObservationLog** [comment]
should be fixed in the commit fd03f07

**Comment by WorldObservationLog** [comment]
> thxx. I found the similar path for aac: moov/trak/mdia/minf/stbl/stsd/enca[0]/esds. But I tried alac way to write it to moov/trak/mdia/minf/stbl/stsd/esds but seems not solving the issue. Might be the internal gpac/mp4box issue you mentioned.

for aac, the esds box is in moov/trak/mdia/minf/stbl/stsd/mp4a/esds
